"""
Consider all integer combinations of ab for $2 \leq a \leq 5$ and $2 \leq b \leq 5$:

$$2^2=4, \quad 2^3=8, \quad 2^4=16, \quad 2^5=32$$
$$3^2=9, \quad 3^3=27, \quad 3^4=81, \quad 3^5=243$$
$$4^2=16, \quad 4^3=64, \quad 4^4=256, \quad 4^5=1024$$
$$5^2=25, \quad 5^3=125, \quad 5^4=625, \quad 5^5=3125$$

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

$$4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125$$

How many distinct terms are in the sequence generated by ab for $2 \leq a \leq 100$ and $2 \leq b \leq 100$?
"""


#c = []
c = set()
N = 100
for a in range(2, N+1):
    for b in range(2, N+1):
        #c.append(a**b)
        c.add(a**b)
cantidad = len(sorted(c))
print(cantidad)  # 9183
