"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, 
for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
what is the value of D?
"""


def f_1():
    N = 10000
    lista = [int(n * (3*n - 1) / 2) for n in range(1, N+1)]
    p = tuple(lista)
    p_set = set(p)
    D = []
    for j in range(N):
        pj = p[j]
        for k in range(N):
            pk = p[k]
            suma = pk + pj
            resta = abs(pk - pj)
            if (suma in p_set) and (resta in p_set):
                D.append(resta)
                #print(pj, pk)
    return D


min(f_1())  # 5482660


# antes cythonmagic
%load_ext Cython


%%cython --annotate
def funcion():
    cdef unsigned int j, k, N
    cdef unsigned long n, suma, resta, pj, pk
    N = 100000
    lista = [int(n * (3*n - 1) / 2) for n in range(1, N+1)]
    p = tuple(lista)
    p_set = set(p)
    D = []
    for j in range(N):
        pj = p[j]
        for k in range(N):
            pk = p[k]
            suma = pk + pj
            resta = abs(pk - pj)
            if (suma in p_set) and (resta in p_set):
                D.append(resta)
                #print(pj, pk)
    return D


%%time
funcion()
