"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


N = 100000
t = set([int(n*(n+1)/2) for n in range(1, N+1)])
p = set([int(n*(3*n-1)/2) for n in range(1, N+1)])
h = set([int(n*(2*n-1)) for n in range(1, N+1)])


lista = [i for i in h if i in t and i in p]
lista[-1]  # 1533776805
